### ISSUE TITLE
DOMDocument::loadHTML() warnings

### ISSUE THREAD

**Issue by AlexeyKosov** [ahmedkaludi/accelerated-mobile-pages#4964]
I noticed a bunch of warnings in the PHP log caused by the AMP plugin:

```
[2021-03-19 21:19:09] Warning: DOMDocument::loadHTML(): Tag amp-img invalid in Entity, line: 1062 in /var/www/blog/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 8407
#0 [internal function]: {closure}()
#1 /var/www/blog/wp-content/plugins/accelerated-mobile-pages/templates/features.php(8407): DOMDocument->loadHTML()
#2 /var/www/blog/wp-includes/class-wp-hook.php(292): ampforwp_include_required_scripts()
#3 /var/www/blog/wp-includes/plugin.php(212): WP_Hook->apply_filters()
#4 /var/www/blog/wp-content/plugins/accelerated-mobile-pages/includes/features/functions.php(246): apply_filters()
#5 [internal function]: ampforwp_the_content_filter_full()
#6 /var/www/blog/wp-includes/functions.php(4757): ob_end_flush()
#7 /var/www/blog/wp-includes/class-wp-hook.php(292): wp_ob_end_flush_all()
#8 /var/www/blog/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters()
#9 /var/www/blog/wp-includes/plugin.php(484): WP_Hook->do_action()
#10 /var/www/blog/wp-includes/load.php(1072): do_action()
#11 [internal function]: shutdown_action_hook()
#12 {main}

[2021-03-19 21:19:09] Warning: DOMDocument::loadHTML(): Tag figure invalid in Entity, line: 1094 in /var/www/blog/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 8407
#0 [internal function]: {closure}()
#1 /var/www/blog/wp-content/plugins/accelerated-mobile-pages/templates/features.php(8407): DOMDocument->loadHTML()
#2 /var/www/blog/wp-includes/class-wp-hook.php(292): ampforwp_include_required_scripts()
#3 /var/www/blog/wp-includes/plugin.php(212): WP_Hook->apply_filters()
#4 /var/www/blog/wp-content/plugins/accelerated-mobile-pages/includes/features/functions.php(246): apply_filters()
#5 [internal function]: ampforwp_the_content_filter_full()
#6 /var/www/blog/wp-includes/functions.php(4757): ob_end_flush()
#7 /var/www/blog/wp-includes/class-wp-hook.php(292): wp_ob_end_flush_all()
#8 /var/www/blog/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters()
#9 /var/www/blog/wp-includes/plugin.php(484): WP_Hook->do_action()
#10 /var/www/blog/wp-includes/load.php(1072): do_action()
#11 [internal function]: shutdown_action_hook()
#12 {main}

[2021-03-19 21:19:09] Warning: DOMDocument::loadHTML(): htmlParseEntityRef: no name in Entity, line: 1138 in /var/www/blog/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 8407
#0 [internal function]: {closure}()
#1 /var/www/blog/wp-content/plugins/accelerated-mobile-pages/templates/features.php(8407): DOMDocument->loadHTML()
#2 /var/www/blog/wp-includes/class-wp-hook.php(292): ampforwp_include_required_scripts()
#3 /var/www/blog/wp-includes/plugin.php(212): WP_Hook->apply_filters()
#4 /var/www/blog/wp-content/plugins/accelerated-mobile-pages/includes/features/functions.php(246): apply_filters()
#5 [internal function]: ampforwp_the_content_filter_full()
#6 /var/www/blog/wp-includes/functions.php(4757): ob_end_flush()
#7 /var/www/blog/wp-includes/class-wp-hook.php(292): wp_ob_end_flush_all()
#8 /var/www/blog/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters()
#9 /var/www/blog/wp-includes/plugin.php(484): WP_Hook->do_action()
#10 /var/www/blog/wp-includes/load.php(1072): do_action()
#11 [internal function]: shutdown_action_hook()
#12 {main}

[2021-03-19 21:19:09] Warning: DOMDocument::loadHTML(): htmlParseEntityRef: expecting ';' in Entity, line: 1149 in /var/www/blog/wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 8407
#0 [internal function]: {closure}()
#1 /var/www/blog/wp-content/plugins/accelerated-mobile-pages/templates/features.php(8407): DOMDocument->loadHTML()
#2 /var/www/blog/wp-includes/class-wp-hook.php(292): ampforwp_include_required_scripts()
#3 /var/www/blog/wp-includes/plugin.php(212): WP_Hook->apply_filters()
#4 /var/www/blog/wp-content/plugins/accelerated-mobile-pages/includes/features/functions.php(246): apply_filters()
#5 [internal function]: ampforwp_the_content_filter_full()
#6 /var/www/blog/wp-includes/functions.php(4757): ob_end_flush()
#7 /var/www/blog/wp-includes/class-wp-hook.php(292): wp_ob_end_flush_all()
#8 /var/www/blog/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters()
#9 /var/www/blog/wp-includes/plugin.php(484): WP_Hook->do_action()
#10 /var/www/blog/wp-includes/load.php(1072): do_action()
#11 [internal function]: shutdown_action_hook()
#12 {main}
```

It's flooded the log and made it almost unusable because of thousands of these warnings.
Is there any way to get rid of those?

---

WordPress 5.7
AMP for WP 1.0.76.7
PHP 7.4.15

**Comment by AlexeyKosov** [comment]
Sorry, it was an issue with my custom logger. It would show warnings even if they were suppressed with `@`
