### ISSUE TITLE
PHP Fatal error: Uncaught ValueError

### ISSUE THREAD

**Issue by Sasirekhamarella** [ahmedkaludi/accelerated-mobile-pages#5174]
```
Error notice: thrown in plugins/accelerated-mobile-pages/templates/features.php on line 8283
PHP Fatal error:  Uncaught ValueError: DOMDocument::loadHTML(): Argument #1 ($source) must not be empty in 
Stack trace:
#0 wp-content/plugins/accelerated-mobile-pages/templates/features.php(8283): DOMDocument->loadHTML('')
#1 /wp-includes/class-wp-hook.php(303): ampforwp_remove_duplicate_canonical('')
#2 wp-includes/plugin.php(189): WP_Hook->apply_filters('', Array)
#3 wp-content/plugins/accelerated-mobile-pages/includes/features/functions.php(280): apply_filters('ampforwp_the_co...', '')
#4 [internal function]: ampforwp_the_content_filter_full('', 9)
#5 wp-includes/functions.php(5107): ob_end_flush()
#6 wp-includes/class-wp-hook.php(303): wp_ob_end_flush_all('')
#7 /wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#8 /wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#9 /wp-includes/load.php(1097): do_action('shutdown')
#10 [internal function]: shutdown_action_hook()
#11 {main}
  thrown in wp-content/plugins/accelerated-mobile-pages/templates/features.php on line 8283





```Reference ticket: https://wordpress.org/support/topic/php-fatal-error-uncaught-valueerror-2/

**Comment by mtoensing** [comment]
new in php8:

The @ operator no longer silences fatal errors

They are silenced with display_errors=Off but they appear in the log

**Comment by Zabi09** [comment]
@mtoensing we have fixed your issue and going to release it in our next update

Here is the fix that you can add and your issue will be solved instantly without waiting for the next update  - https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/d8be268c6

**Comment by Zabi09** [comment]
Pushed in 1.0.77.31
