### ISSUE TITLE
Uncaught ValueError: DOMDocument::loadHTML(): Argument #1 ($source) must not be empty

### ISSUE THREAD

**Issue by kn007** [ahmedkaludi/accelerated-mobile-pages#5512]
After upgrade plugin to 1.0.88 (1.0.88.1) (After 2023/08/22 15:12:02 GMT)

```
PHP Fatal error:  Uncaught ValueError: DOMDocument::loadHTML(): Argument #1 ($source) must not be empty in /***/wp-content/plugins/accelerated-mobile-pages/templates/features.php:8557
Stack trace:
#0 /***/wp-content/plugins/accelerated-mobile-pages/templates/features.php(8557): DOMDocument->loadHTML()
#1 /***/wp-includes/class-wp-hook.php(310): ampforwp_remove_unwanted_code()
#2 /***/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#3 /***/wp-content/plugins/accelerated-mobile-pages/includes/features/functions.php(314): apply_filters()
#4 [internal function]: ampforwp_the_content_filter_full()
#5 /***/wp-includes/functions.php(5349): ob_end_flush()
#6 /***/wp-includes/class-wp-hook.php(310): wp_ob_end_flush_all()
#7 /***/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#8 /***/wp-includes/plugin.php(517): WP_Hook->do_action()
```

https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/5174

**Comment by akshaywali** [comment]
pushed in update 1.0.89
