### ISSUE TITLE
Php error on user end.

### ISSUE THREAD

**Issue by Sdaud1950** [ahmedkaludi/accelerated-mobile-pages#5642]
Php error on user end.
 PHP Fatal error: Uncaught Error: Undefined constant "AMP__DIR__" in /home/customer/www/public_html/wp-content/plugins/amp-woocommerce-pro/license/license-activation.php:17
Stack trace:
#0 /home/customer/www/public_html/wp-includes/class-wp-hook.php(324): amp_woocommerce_get_extension_licence_activate_update('')
#1 /home/customer/www//public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#2 /home/customer/www//public_html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /home/customer/www//public_html/wp-admin/admin-ajax.php(192): do_action('wp_ajax_ampforw...')
#4 {main}
thrown in /home/customer/www//public_html/wp-content/plugins/amp-woocommerce-pro/license/license-activation.php on line 17

Ref ticket:https://magazine3.in/conversation/312334?folder_id=29

**Comment by akshaywali** [comment]
pushed in AMP for WP 1.1.1
